# server:
#     port: 8088

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/public-transportation-query-system?useSSL=false&characterEncoding=UTF-8
        username: root
        password: LmzwTvA1p5Bds3DODi$b2bfe2b68ef2esdf9b86dd354e00d3c3c7f533ce18fe8a6f33f7c3af52396b1bb
    security:
        user:
            name: root
            password: root
            roles:
            - user
            - admin

springdoc:
    swagger-ui:
        enabled: true
        path: /api/docs
    api-docs:
        enabled: true
        path: /api/api-docs
    show-login-endpoint: true

# mybatis-plus:
#     mapper-locations: classpath:/mapper/*.xml
#     configuration:
#         map-underscore-to-camel-case: true
        # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
